name: rrs-es
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - ipykernel
  - pip
  - pip:
    - numpy<2.0.0
    - essentia
    - tqdm
    - wandb
    - matplotlib
    - omegaconf
    - hydra-core
    - pandas
    - scikit-learn
    - yt-dlp