export CUDA_VISIBLE_DEVICES=0
python3 train.py \
  data=cluster_reduced \
  nn_params=cluster_encoder \
  nn_params.dim=256 \
  nn_params.depth=8 \
  train_params.batch_size=256 \
  train_params.num_iter=24000000 \
  train_params.num_iter_per_train_log=10 \
  train_params.num_iter_per_validation=3000 \
  train_params.num_iter_per_inference=9000 \
  train_params.num_iter_per_checkpoint=10000 \
  train_params.max_length=50 \
  train_params.scheduler=cosineannealingwarmuprestarts \
  inference_params.num_inference=10 \
  inference_params.infer_length=100 \
  inference_params.sampling.method=argmax \
  inference_params.sampling.temperature=1.5 \
  general.log=true \
  general.infer=true