export CUDA_VISIBLE_DEVICES=0
export CUDA_LAUNCH_BLOCKING=1
python3 train.py \
  data=cluster_debug \
  nn_params=cluster_encoder \
  nn_params.dim=512 \
  nn_params.depth=8 \
  train_params.device='cuda' \
  train_params.batch_size=512 \
  train_params.num_iter=1000 \
  train_params.num_iter_per_train_log=10 \
  train_params.num_iter_per_validation=500 \
  train_params.num_iter_per_inference=100 \
  train_params.num_iter_per_checkpoint=1000 \
  train_params.max_length=50 \
  inference_params.num_inference=3 \
  inference_params.sampling.method=argmax \
  inference_params.sampling.temperature=1.5 \
  general.debug=true \
  general.log=false \
  general.infer=true